# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deepPRC',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/deepPRC',
                'lib_path': 'deepPRC'},
  'syms': {'deepPRC.core': {'deepPRC.core.foo': ('core.html#foo', 'deepPRC/core.py')}}}
